# Generated by Django 3.1.4 on 2020-12-30 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('post_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('post_type', models.CharField(choices=[('T', 'Text'), ('I', 'Image'), ('V', 'Video'), ('A', 'Audio')], default='T', max_length=2)),
                ('title', models.CharField(default='', max_length=500, null=True)),
                ('description', models.CharField(default='', max_length=1000, null=True)),
                ('date_posted', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('media', models.FileField(blank=True, default='', null=True, upload_to='media/post')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
