# Generated by Django 3.1.4 on 2021-01-04 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_shoutcomment_shoutlike'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoutReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(max_length=256, null=True)),
                ('shout_id', models.ForeignKey(default='', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ReportedPost', to='posts.posts')),
                ('user_id', models.ForeignKey(default='', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Report_User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
