# Generated by Django 3.1.4 on 2021-01-04 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_shoutreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoutreport',
            name='shout_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ReportedPost', to='posts.posts'),
        ),
        migrations.AlterField(
            model_name='shoutreport',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Report_User', to=settings.AUTH_USER_MODEL),
        ),
    ]
