# Generated by Django 3.1.4 on 2021-01-05 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210104_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoutcomment',
            name='updated_at',
        ),
    ]
