# Generated by Django 3.1.4 on 2021-01-05 05:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0005_remove_shoutcomment_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoutcomment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='shoutcomment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shoutcomment',
            name='shout_id',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserPost', to='posts.posts'),
        ),
        migrations.AlterField(
            model_name='shoutcomment',
            name='user_id',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Comment_User', to=settings.AUTH_USER_MODEL),
        ),
    ]
