# Generated by Django 3.1.4 on 2021-01-05 05:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20210105_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoutcomment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
